# development config
version: "3.4"
services:
  web:
    command: npm run dev
    image: "${IMAGE_PREFIX}/web_dev:$IMAGE_TAG"
    build:
      target: dev
    environment:
      - NODE_ENV=development
      - WEBSITE_URL=http://localhost:3001
      - DOMAIN=loc.$PROJECT.com
    volumes:
      - ./web:/app
      # use node_modules & .next from container
      - /app/node_modules
      - /app/.next
    ports:
      - "9230:9229"
      - "3001:3000"
    logging:
      driver: "json-file"
    healthcheck: # check health of production build only
      disable: true
  dbmate:
    volumes:
      - ./dbmate:/app/db
  db:
    ports:
      - "5432:5432"
    # uncomment to log all SQL queries
    # command: ['postgres', '-c', 'log_statement=all']
    logging:
      driver: "json-file"
  e2e:
    image: "${IMAGE_PREFIX}/e2e:$IMAGE_TAG"
    build:
      context: ./e2e
    volumes:
      - ./e2e:/app
      - /app/node_modules
    environment:
      - E2E_TEST_URL
      - E2E_HEADLESS
    logging:
      driver: "json-file"
    user: ${USER_ID}
    depends_on:
      - web
    ports:
      - "3333:3333"
      - "2999:2999"
